name: 'SPC OIDC Login'
description: 'GitHub Actions OIDC login for SPC'
inputs:
  role_arn:
    description: 'SPC IAM Role ARN'
    required: true
  sts_endpoint:
    description: 'STS endpoint URL'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.role_arn }}
    - ${{ inputs.sts_endpoint }}
